# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
    - repository: EmptyRepo
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/azure-pipelines-repo-dont-remove-please

trigger:
  batch: true
  branches:
    exclude:
      - master
  tags:
    exclude:
      - v*.*.*

pool:
  vmImage: "Ubuntu-22.04"

steps:
  - checkout: self
  - checkout: EmptyRepo
    persistCredentials: true
    clean: true
    fetchDepth: 1

  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/survey-pdf/"
      Contents: "package.json"
      TargetFolder: "$(Build.SourcesDirectory)/Temp/"
      OverWrite: true
    displayName: "Copy package.json for cache key"
  - task: Cache@2
    inputs:
      key: "npm-cache-pdf | $(Build.SourcesDirectory)/Temp/package.json"
      path: $(Build.SourcesDirectory)/survey-pdf/node_modules
      cacheHitVar: NPM_CACHE_RESTORED
    displayName: Cache NPM

  - powershell: |
      $env:GIT_REDIRECT_STDERR = '2>&1'
      git config --global user.email "surveyjs.org@gmail.com"
      git config --global user.name "surveyjsdeveloper"
    displayName: "set up Git config"

  - task: Npm@1
    displayName: "NPM install"
    inputs:
      command: install
      verbose: false
      workingDir: $(Build.SourcesDirectory)/survey-pdf
    condition: ne(variables.NPM_CACHE_RESTORED, 'true')

  - script: |
      cd $(Build.SourcesDirectory)/survey-pdf
      npm run lint
    displayName: "run lint command"

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: "specific"
      project: "af2804d2-859a-4705-9ef5-cdf46d1d5d4f"
      pipeline: "56"
      specificBuildWithTriggering: true
      buildVersionToDownload: "latest"
      downloadType: "single"
      artifactName: "SurveyJSLibraryBuildCore"
      downloadPath: "$(System.ArtifactsDirectory)"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(System.ArtifactsDirectory)/SurveyJSLibraryBuildCore/packages/survey-core"
      Contents: "**"
      TargetFolder: "$(Build.SourcesDirectory)/survey-pdf/node_modules/survey-core"
      OverWrite: true

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: "specific"
      project: "af2804d2-859a-4705-9ef5-cdf46d1d5d4f"
      pipeline: "42"
      specificBuildWithTriggering: true
      buildVersionToDownload: "latest"
      downloadType: "single"
      artifactName: "SurveyJSWidgetsBuild"
      downloadPath: "$(System.ArtifactsDirectory)"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(System.ArtifactsDirectory)/SurveyJSWidgetsBuild/packages/survey-widgets"
      Contents: "**"
      TargetFolder: "$(Build.SourcesDirectory)/survey-pdf/node_modules/surveyjs-widgets"
      OverWrite: true

  - script: |
      cd $(Build.SourcesDirectory)/survey-pdf
      npm run build:all
    displayName: "build"

  - script: |
      cd $(Build.SourcesDirectory)/survey-pdf
      npm test
    displayName: "unit tests"

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura # or JaCoCo
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/*coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/**/coverage"

  - script: |
      cd $(Build.SourcesDirectory)/survey-pdf
      npm run doc_gen
    displayName: "generate docs"
