// Auto-generated theme: base-layout
export default {
    '--sjs2-is-panelless': 'false',
    '--sjs2-typography-font-family-text': 'Open Sans',
    '--sjs2-typography-font-family-code': 'DM Mono',
    '--sjs2-typography-font-family-component-input-content': 'var(--sjs2-typography-font-family-text)',
    '--sjs2-typography-font-family-component-question-title': 'var(--sjs2-typography-font-family-text)',
    '--sjs2-typography-font-family-component-question-description': 'var(--sjs2-typography-font-family-text)',
    '--sjs2-typography-font-family-component-page-title': 'var(--sjs2-typography-font-family-text)',
    '--sjs2-typography-font-family-component-page-description': 'var(--sjs2-typography-font-family-text)',
    '--sjs2-typography-font-family-component-header-title': 'var(--sjs2-typography-font-family-text)',
    '--sjs2-typography-font-family-component-header-description': 'var(--sjs2-typography-font-family-text)',
    '--sjs2-typography-font-size-small': 'var(--sjs2-font-size-x150)',
    '--sjs2-typography-font-size-default': 'var(--sjs2-font-size-x200)',
    '--sjs2-typography-font-size-medium': 'var(--sjs2-font-size-x300)',
    '--sjs2-typography-font-size-large': 'var(--sjs2-font-size-x400)',
    '--sjs2-typography-font-size-component-input-content': 'var(--sjs2-typography-font-size-default)',
    '--sjs2-typography-font-size-component-question-title': 'var(--sjs2-typography-font-size-default)',
    '--sjs2-typography-font-size-component-question-description': 'var(--sjs2-typography-font-size-default)',
    '--sjs2-typography-font-size-component-page-title': 'var(--sjs2-typography-font-size-medium)',
    '--sjs2-typography-font-size-component-page-description': 'var(--sjs2-typography-font-size-default)',
    '--sjs2-typography-font-size-component-header-title': 'var(--sjs2-typography-font-size-large)',
    '--sjs2-typography-font-size-component-header-description': 'var(--sjs2-typography-font-size-medium)',
    '--sjs2-typography-line-height-small': 'var(--sjs2-line-height-x200)',
    '--sjs2-typography-line-height-default': 'var(--sjs2-line-height-x300)',
    '--sjs2-typography-line-height-medium': 'var(--sjs2-line-height-x400)',
    '--sjs2-typography-line-height-large': 'var(--sjs2-line-height-x500)',
    '--sjs2-typography-line-height-component-input-content': 'var(--sjs2-typography-line-height-default)',
    '--sjs2-typography-line-height-component-question-title': 'var(--sjs2-typography-line-height-default)',
    '--sjs2-typography-line-height-component-question-description': 'var(--sjs2-typography-line-height-default)',
    '--sjs2-typography-line-height-component-page-title': 'var(--sjs2-typography-line-height-medium)',
    '--sjs2-typography-line-height-component-page-description': 'var(--sjs2-typography-line-height-default)',
    '--sjs2-typography-line-height-component-header-title': 'var(--sjs2-typography-line-height-large)',
    '--sjs2-typography-line-height-component-header-description': 'var(--sjs2-typography-line-height-medium)',
    '--sjs2-typography-font-weight-basic': 'var(--sjs2-font-weight-regular)',
    '--sjs2-typography-font-weight-strong': 'var(--sjs2-font-weight-semibold)',
    '--sjs2-typography-font-weight-component-input-content': 'var(--sjs2-typography-font-weight-basic)',
    '--sjs2-typography-font-weight-component-question-title': 'var(--sjs2-typography-font-weight-strong)',
    '--sjs2-typography-font-weight-component-question-description': 'var(--sjs2-typography-font-weight-basic)',
    '--sjs2-typography-font-weight-component-page-title': 'var(--sjs2-typography-font-weight-strong)',
    '--sjs2-typography-font-weight-component-page-description': 'var(--sjs2-typography-font-weight-basic)',
    '--sjs2-typography-font-weight-component-header-title': 'var(--sjs2-typography-font-weight-strong)',
    '--sjs2-typography-font-weight-component-header-description': 'var(--sjs2-typography-font-weight-basic)'
};
