export type IStyles = { [index: string]: any }
export function getDefaultStyles (baseSize: number) {
    return {
        titleFontSize: baseSize * 4,
        titleFontStyle: 'bold',
        titleFontColor: '#000',
        descriptionFontSize: 2,
        descriptionGap: baseSize * 1.5,
        contentGap: baseSize * 4.0,
        question: {
            headerBorderWidth: 0,
            headerPadding: 0,
            titleLeftWidthPers: Math.E / 10.0,
            titleLineHeight: baseSize * 3,
            titleFontSize: baseSize * 2,
            titleFontStyle: 'normal',
            titleFontColor: '#000',
            contentGapVertical: baseSize * 0.5,
            contentGapHorizontal: baseSize * 1.0,
            contentIndent: 0,
            descriptionGap: baseSize * 0.0625,
            descriptionFontSize: baseSize * 2,
            gapBetweenItemText: baseSize * 0.25,
            gapBetweenColumns: baseSize * 1.5,
            gapBetweenRows: baseSize * 0.25,
            wrapperPadding: [baseSize * 0.5, baseSize],
            wrapperBorderWidth: baseSize * 0.125,
            wrapperBorderColor: '#000',
            inputBorderColor: '#000',
            inputBorderWidth: 0,
            inputFontColor: '#000',
            inputFontSize: baseSize * 2.5,
            commentBorderColor: '#000',
            commentBorderWidth: 0,
            commentFontColor: '#000',
            commentFontSize: baseSize * 2.5,
            commentLineHeight: baseSize * 3
        },
        panel: {
            wrapperPadding: 0,
            wrapperBorderWidth: 0,
            titleFontSize: baseSize * 2,
            titleFontStyle: 'bold',
            titleFontColor: '#000',
            titleLineHeight: baseSize * 3.5,
            gapBetweenRows: 0,
            gapBetweenElements: 0,
            contentGap: 0,
            panelDescriptionGap: baseSize * 0.25,
            descriptionFontSize: baseSize * 2,
            descriptionGap: baseSize * 0.5,
            headerPadding: [baseSize * 0.5, baseSize],
            headerBorderWidth: baseSize * 0.125,
            headerBorderColor: '#000',
            headerBackgroundColor: '#E5E5E5'
        },
        page: {
            headerBorderWidth: 0,
            headerPadding: 0,
            contentGap: baseSize * 2,
            headerBackgroundColor: '#fff',
            gapBetweenRows: 0,
            gapBetweenElements: 0,
            titleFontSize: baseSize * 2,
            titleFontStyle: 'bold',
            titleFontColor: '#000'
        },
        selectbase: {
            columnMinWidth: baseSize * 5,
            gapBetweenColumns: 1.5,
            gapBetweenRows: baseSize,
            gapBetweenItemText: baseSize,
            contentGapVertical: baseSize * 1,
            inputWidth: baseSize * 2,
            inputHeight: baseSize * 2,
            labelFontSize: baseSize * 2.5,
            labelLineHeight: baseSize * 3,
            labelFontStyle: 'normal',
            labelFontColor: '#000',
            inputBorderWidth: baseSize * 0.125,
            inputFontSize: baseSize * 1.25,
            inputFont: 'zapfdingbats',
        },
        checkbox: {
            inputSymbol: '3',
        },
        radiogroup: {
            inputSymbol: 'l',
        },
        matrixbase: {
            columnMinWidth: baseSize * 12.5,
            cellBorderWidth: baseSize * 0.125,
            cellBorderColor: '#000',
            cellPadding: [baseSize * 0.5, baseSize],
            headerBorderWidth: baseSize * 0.125,
            headerPadding: [baseSize * 0.5, baseSize],
            headerBackgroundColor: '#E5E5E5',
            headerBorderColor: '#000',
            contentGapVertical: 0,
            wrapperPadding: 0,
            wrapperBorderWidth: 0,
            titleFontStyle: 'bold',
            gapBetweenColumns: 0,
            gapBetweenRows: 0,
            inputHeight: baseSize * 2,
            inputWidth: baseSize * 2,
            rowTitleFontSize: baseSize * 2,
            rowTitleLineHeight: baseSize * 3,
            rowTitleFontStyle: 'normal',
            rowTitleFontColor: '#000',
            headerFontSize: baseSize * 2,
            headerLineHeight: baseSize * 3,
            headerFontStyle: 'normal',
            headerFontColor: '#000',

            verticalHeaderFontSize: baseSize * 2,
            verticalHeaderLineHeight: baseSize * 3,
            verticalHeaderFontStyle: 'normal',
            verticalHeaderFontColor: '#000',
            verticalRowTitleFontSize: baseSize * 2,
            verticalRowTitleLineHeight: baseSize * 3,
            verticalRowTitleFontStyle: 'bold',
            verticalRowTitleFontColor: '#000',
            verticalGapBetweenItems: baseSize,
            verticalGapBetweenRowTitleQuestion: baseSize * 0.5,
            verticalCellRowTitleBackgroundColor: '#E5E5E5'
        },
        matrix: {
            inputBorderWidth: baseSize * 0.125,
            radiomarkSymbol: 'l',
            radiomarkFontSize: baseSize * 2,
            radiomarkFont: 'zapfdingbats',
            checkmarkFontSize: baseSize * 2,
            checkmarkFont: 'zapfdingbats',
            checkmarkSymbol: '3',
            verticalHeaderFontSize: baseSize * 2.5,
            verticalRowTitleFontStyle: 'normal',
            verticalGapBetweenItemText: baseSize,
        },
        multipletext: {
            itemTitleWidthPers: Math.E / 10.0,
            labelFontSize: baseSize * 2.5,
            labelLineHeight: baseSize * 3,
            labelFontStyle: 'normal',
            labelFontColor: '#000',
            gapBetweenColumns: 1.5,
            rowsGap: baseSize * 0.195
        },
        rating: {
            inputHeight: baseSize * 2,
            inputWidth: baseSize * 2,
            itemMinWidth: baseSize * 3,
            gapBetweenColumns: baseSize * 0.25,
            gapBetweenRows: baseSize * 0.25,
            inputSymbol: 'l',
            gapBetweenItemText: baseSize,
            gapBetweenItemTextVertical: 0,
            labelFontSize: baseSize * 2.5,
            labelLineHeight: baseSize * 3,
            labelFontStyle: 'normal',
            labelFontColor: '#000',
            radiomarkFont: 'zapfdingbats',
            inputBorderWidth: baseSize * 0.125,
            inputFontSize: baseSize * 1.25
        },
        ranking: {
            inputHeight: baseSize * 2,
            inputWidth: baseSize * 2,
            gapBetweenColumns: baseSize * 1.5,
            gapBetweenRows: baseSize * 0.25,
            checkmarkFontSize: baseSize * 2,
        },
        slider: {
            inputFontSize: baseSize * 2.5,
            inputLineHeight: baseSize * 3,
            gapBetweenColumns: baseSize * 1.5,
        },
        dropdown: {
            contentGapVertical: baseSize * 0.5,
            gapBetweenRows: baseSize * 0.25,
            inputFontSize: baseSize * 2.5,
            inputLineHeight: baseSize * 3,
            inputBorderWidth: baseSize * 0
        },
        file: {
            imageGap: baseSize * 0.195,
            itemMinWidth: baseSize * 5,
            labelFontColor: '#0000EE',
            labelFontStyle: 'normal',
            labelFontSize: baseSize * 2.5,
            labelLineHeight: baseSize * 3,
            defaultImageFit: 'contain',
        },
        paneldynamic: {
            titleFontStyle: 'bold',
            headerBorderWidth: baseSize * 0.125,
            headerPadding: [baseSize * 0.5, baseSize],
            headerBackgroundColor: '#E5E5E5',
            headerBorderColor: '#000',
            contentGapVertical: 0,
            gapBetweenPanels: 0,
            wrapperPadding: 0,
            wrapperBorderWidth: 0,
        },
        boolean: {
            checkmarkFontSize: baseSize * 2,
            checkmarkFont: 'zapfdingbats',
            checkmarkSymbol: '3',
            inputWidth: baseSize * 2,
            inputHeight: baseSize * 2,
            inputBorderWidth: baseSize * 0.125,
            labelFontSize: baseSize * 2.5,
            labelLineHeight: baseSize * 3,
            labelFontStyle: 'normal',
            labelFontColor: '#000',
            gapBetweenItemText: baseSize,
        },
        imagepicker: {
            checkmarkFontSize: baseSize * 2,
            checkmarkFont: 'zapfdingbats',
            checkmarkSymbol: '3',
            radiomarkSymbol: 'l',
            radiomarkFontSize: baseSize * 2,
            radiomarkFont: 'zapfdingbats',
            inputHeight: baseSize * 2,
            gapBetweenColumns: baseSize * 1.5,
            gapBetweenRows: baseSize * 1.5,
            imageRatio: 4 / 3,
            imageMinWidth: baseSize * 12.5,
            imageMaxWidth: baseSize * 37.5
        },
        textbase: {
            inputFontSize: baseSize * 2.5,
            inputLineHeight: baseSize * 3
        },
        expression: {
            inputFontSize: baseSize * 2.5,
            inputLineHeight: baseSize * 3
        },
        html: {
            fontSize: baseSize * 2,
            fontColor: '#000',
            lineHeight: baseSize * 3.5,
        }
    };
}

